### ISSUE TITLE
Voila Gallery

### ISSUE THREAD

**Issue by jtpio** [danielfrg/jupyter-flex#17]
This is a cool project!

What do you think about adding it to the [Voila Gallery](https://voila-gallery.org)? So it can be showcased as an example.

The example could be the Movie Explorer, using this Binder link: https://mybinder.org/v2/gh/danielfrg/jupyter-flex/b202af9ea05029a39e667be9da1f72257a6a82b3?urlpath=%2Fvoila%2Frender%2Fexamples%2Fmovie-explorer.ipynb

We would need to add the following snippet to `_data/gallery.yaml` in https://github.com/voila-gallery/voila-gallery.github.io:

```yaml
- title: jupyter-flex
  description: Easy interactive dashboards for Jupyter
  url: voila/render/examples/movie-explorer.ipynb
  ref: b202af9ea05029a39e667be9da1f72257a6a82b3
  repo_url: https://github.com/danielfrg/jupyter-flex
  image_url: https://jupyter-flex.extrapolations.dev/assets/img/screenshots/movie-explorer.png
```
